### ISSUE TITLE
Test failures in Plone 5.0.7

### ISSUE THREAD

**Issue by jensens** [collective/collective.z3cform.datagridfield#61]
There are TravisCI test failures on master branch. These tests are running fine in 5.0.6. Any idea what changed from 5.0.6 to 5.0.7 that makes the test setup break?

**Comment by hvelarde** [comment]
I think that could be related with some changes on the dependencies of plone.app.upgrades, and it's only affecting the testing infrastructure.

CC @mauritsvanrees

**Comment by mauritsvanrees** [comment]
As another data point, the PloneFormGen tests are failing too when going from 5.0.6 to 5.0.7. The error seems totally different from the one here, though it might have the same root cause.
See https://github.com/smcmahon/Products.PloneFormGen/issues/197 and https://github.com/smcmahon/Products.PloneFormGen/issues/198
I haven't dived into this. In all cases it seems to only affect tests, not live sites.
